- name: Create skeleton directory
  file: path=/opt/skeleton state=directory

- name: Download JAR File to the skeleton directory
  maven_artifact:
    group_id: "{{ group_id }}"
    artifact_id: "{{ artifact_id }}"
    extension: jar
    version: "{{ artifact_version }}""
    repository_url: "{{ repository_url }}"
    dest: /opt/skeleton/
    mode: 0755

- name: Ensure app is configured
  template:
    src: application.properties.j2
    dest: /opt/skeleton/application.properties

- name: Ensure logging is configured
  template:
    src: logback-spring.xml.j2
    dest: /opt/skeleton/logback-spring.xml

- name: Install skeleton systemd unit file
  template: src=skeleton.service.j2 dest=/etc/systemd/system/skeleton.service

- name: Start skeleton
  systemd: state=restarted name=skeleton daemon_reload=yes
